---
name: Makefile (test download scripts)

"on":
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install xz as it is required to unzip the shellcheck binary
        run: sudo apt-get install -y xz-utils
      - name: Run make test locally for the download scripts
        run: make -C scripts/download test-local || (cat scripts/download/tests/test_results.log && exit 1)
